sylius_grid:
    templates:
        bulk_action:
            recalculate: "@SetonoSyliusBulkSpecialsPlugin/Grid/BulkAction/recalculate.html.twig"
    grids:
        setono_sylius_bulk_specials_admin_special:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_bulk_specials.model.special.class%"
            sorting:
                priority: desc
            fields:
                priority:
                    type: twig
                    label: sylius.ui.priority
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/position.html.twig"
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: twig
                    label: sylius.ui.name
                    path: .
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/nameAndDescription.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, name]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
                    recalculate:
                        type: recalculate
                        label: setono_sylius_bulk_specials.ui.bulk_action.special.recalculate
                        options:
                            link:
                                route: setono_sylius_bulk_specials_admin_special_bulk_recalculate
