setono_sylius_bulk_discount_admin_discount:
    resource: |
        alias: setono_sylius_bulk_discount.discount
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: setono_sylius_bulk_discount_admin_discount
        permission: true
        vars:
            all:
                subheader: setono_sylius_bulk_discount.ui.manage_discounts
                templates:
                    form: "@SetonoSyliusBulkDiscountPlugin/Admin/Discount/_form.html.twig"
            index:
                icon: in cart
            update:
                templates:
                    form: "@SetonoSyliusBulkDiscountPlugin/Admin/Discount/_form.html.twig"
    type: sylius.resource
